---
language: python
python: "3.6.9"

# Use the new container infrastructure
sudo: false

before_install:
  - >
    sudo apt-get -y -q remove
    docker
    docker-engine
    docker.io
    containerd
    runc
  - sudo apt -q update
  - >
    sudo apt-get install
    apt-transport-https
    ca-certificates
    curl
    gnupg-agent
    software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - >
    sudo add-apt-repository
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu
    $(lsb_release -cs)
    stable"
  - sudo apt -q update

# Install ansible
addons:
  apt:
    packages:
    - python3-pip
    - docker-ce
    - docker-ce-cli
    - containerd.io

install:
  # Install ansible
  - pip install ansible molecule docker

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
